### ISSUE TITLE
Missing messages inside messages

### ISSUE THREAD

**Issue by maxned** [arkadiyt/protodump#1]
I was looking for something like this just recently and this is a huge help for a project I'm working on! Thank you!

One thing I've noticed though is that it does not export messages within messages. In the app I'm trying to export the proto files from, there are some missing message types. Would it be possible to add this functionality to the export as well?

**Comment by arkadiyt** [comment]
Should be fixed now, let me know if it's working for you

**Comment by maxned** [comment]
It's perfect! Working great now. Thank you very much!
