### ISSUE TITLE
Weird output with optionals

### ISSUE THREAD

**Issue by WolfDan** [arkadiyt/protodump#11]
Hello, I'm experiencing weird outputs with optional fields when generating the proto file with a binary descriptor 

the output is the following: 

```
message Error {
    enum Reason {
      UNKNOWN_AUTH_ERROR = 0;
      ALREADY_CONNECTED = 1;
    }

    <namespace>.Reason reason = 1;
    oneof _ban_end_date {
      optional string ban_end_date = 2;
    }
    oneof _required_version {
      optional string required_version = 3;
    }
  }
```

the problem is in this piece of code:

```
namespace.Reason reason = 1;
oneof _ban_end_date {
  optional string ban_end_date = 2;
}
oneof _required_version {
  optional string required_version = 3;
}
```

Which I think a more valid output should be something like this without the `oneof` 🤔

```
namespace.Reason reason = 1;
optional string ban_end_date = 2;
optional string required_version = 3;
```

Is my expectancy for this wrong? the `oneof` feels wrong in that context because is always optional so you wont need the `oneof`

Thank you!

**Comment by arkadiyt** [comment]
Could you share a file that exhibits this behavior?

**Comment by WolfDan** [comment]
[proto.zip](https://github.com/user-attachments/files/17016252/proto.zip)

Sure! Here's the binary I tried to convert to a protofile (wanted to send it directly but github requires a zip file :p)

**Comment by WolfDan** [comment]
@arkadiyt I think this had to do with `IsSynthetic` at https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect#OneofDescriptor 

If this is true then it should be a normal `optional` when it's a proto3 file, otherwise it's a `oneof` in proto2, I found out about it while working on rust they have this on they documentation 

https://docs.rs/protobuf/3.5.1/protobuf/descriptor/struct.FieldDescriptorProto.html#structfield.proto3_optional

**Comment by arkadiyt** [comment]
Thanks for the pointer - this should be fixed on main now, please lemme know if it's not
