### ISSUE TITLE
No output while dumping Apple Maps

### ISSUE THREAD

**Issue by WordlessEcho** [arkadiyt/protodump#9]
I was trying to protodump Apple Maps. First at macOS 11.7.10:
```
$ file /System/Applications/Maps.app/Contents/MacOS/Maps
/System/Applications/Maps.app/Contents/MacOS/Maps: Mach-O universal binary with 2 architectures: [X86_64:Mach-O 64-bit executable X86_64] [arm64e]
/System/Applications/Maps.app/Contents/MacOS/Maps (for architecture X86_64): Mach-O 64-bit executable X86_64
/System/Applications/Maps.app/Contents/MacOS/Maps (for architecture arm64e): Mach-O 64-bit executable arm64e

$ protodump -file /System/Applications/Maps.app/Contents/MacOS/Maps -output ./out -v
```
I got nothing returned. So I try again on iOS 12.5.7 version:
```
$ file ~/Downloads/Maps
~/Downloads/Maps: Mach-O 64-bit bundle arm64

$ protodump -file ~/Downloads/Maps -output ~/Downloads/out -v
```
Still nothing returned. Anything I can do for next?

**Comment by arkadiyt** [comment]
The way that protodump works, it needs serialized file descriptors in the binary to parse out. If Apple Maps was written with a protoc compiler that doesn't support that (for instance, [swift-protobuf](https://github.com/apple/swift-protobuf/issues/1029)?) then there can't be any proto outputs
